version: '3'

services:
  mqtt-cliente:
    container_name: mqtt-cliente 
    build:
      context: .
      dockerfile: DockerFile
    links:
      - mqtt
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    
    ports:
      - 1883:1883
      - 9001:9001


