apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels: 
    service: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mqtt
  template:
    metadata:
      labels:
        service: mqtt
    spec:
      containers:
      - image: eclipse-mosquitto
        name: mqtt
        ports:
        - containerPort: 1883
        - containerPort: 9001
      restartPolicy: Always
     
