apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    io.kompose.service: mqtt
status:
  loadBalancer: {}
