apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mqtt
    spec:
      containers:
      - image: eclipse-mosquitto
        imagePullPolicy: ""
        name: mqtt
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /mosquitto/config
          name: mqtt-claim0
        - mountPath: /mosquitto/data
          name: mqtt-claim1
        - mountPath: /mosquitto/log
          name: mqtt-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mqtt-claim0
        persistentVolumeClaim:
          claimName: mqtt-claim0
      - name: mqtt-claim1
        persistentVolumeClaim:
          claimName: mqtt-claim1
      - name: mqtt-claim2
        persistentVolumeClaim:
          claimName: mqtt-claim2
status: {}
