apiVersion: v1
kind: Service
metadata:
 name: mqtt-cluster-ip-service
 labels:
   app: mqtt
spec:
  type: ClusterIP
  ports:
  - name: puerto1
    port: 1883
    targetPort: 1883
  - name: puerto2 
    port: 9001
    targetPort: 9001
  selector:
    app: mqtt

